name: Speclj Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Prepare dotnet
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Prepare Clojure CLR
        run: |
          dotnet tool install --global Clojure.Main --version 1.12.0-alpha10
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha5

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Clojure CLI
        run: curl -O https://download.clojure.org/install/linux-install-1.11.1.1119.sh && chmod +x linux-install-1.11.1.1119.sh && sudo ./linux-install-1.11.1.1119.sh

      - name: Build JAR
        run: clojure -T:build javac

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Clojure JVM Tests
        run: clojure -M:test:spec

      - name: Run Clojure CLR Tests
        run: cljr -M:test:spec

      - name: Run ClojureScript Tests
        run: clojure -M:test:cljs ci
