name: Speclj Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Install Babashka
        run: |
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install

      - name: Install Clojure CLI
        run: bb install-clj

      - name: Prepare dotnet
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Prepare Clojure CLR
        run: bb install-cljr

      - name: Cache Clojure Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-deps-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build JAR
        run: clojure -T:build javac

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Clojure JVM Tests
        run: clojure -M:test:spec

      - name: Run Babashka Tests
        run: bb spec

      - name: Run Clojure CLR Tests
        run: cljr -M:test:spec

      - name: Run ClojureScript Tests
        run: clojure -M:test:cljs ci
